# Generated by Django 5.2.1 on 2025-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('course', models.CharField(max_length=200)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
