# Generated by Django 5.2.1 on 2025-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
